defaults:
  - __init__

_target_: lexikanon.pipe.tokenize.extract_tokens
tokenizer_config_name: simple
num_workers: 1
batched: true
batch_size: 1000
token_col: tokenizedText
extracted_col: extractedTokens
nouns_only: false
postags:
stop_postags:
strip_pos: true
postag_delim:
postag_length:
remove_columns:
load_from_cache_file: true
num_heads: 3
num_tails: 3
verbose: ${oc.select:..verbose, false}
