_target_: lexikanon.pipes.similarity.find_similar_docs_by_clustering
num_workers: 2
min_num_docs: 5
percentile: 80
distance_threshold: null
linkage: average
grouping_freq: W
grouping_name: Week
timestamp_col: timestamp
token_col: tokens
id_col: id
cluster_col: cluster
duplicate_col: duplicate
dist_fig_col: dist_fig
output_dir: .
show_fig: false
save_fig: false
verbose: false
