_config_group_: stopwords
_config_name_: __init__
_target_: lexikanon.stopwords.Stopwords
name: stopwords
lowercase: true
stopwords_fn:
stopwords_list:
stopwords_path:
nltk_stopwords_lang:
verbose: False
