_target_: lexikanon.tokenizers.nltk.NLTKTagger
_config_name_: nltk
_config_group_: /tokenizer/tagger
tagset: null
language: english
lemmatize: false
stem: true
lemmatizer:
  _target_: nltk.stem.WordNetLemmatizer
stemmer:
  _target_: nltk.stem.PorterStemmer
verbose: false
