defaults:
  - __init__
  - tagger: mecab

_config_name_: mecab
_target_: lexikanon.tokenizers.MecabTokenizer
flatten: true
noun_postags:
  - NNG
  - NNP
  - XSN
  - SL
  - XR
  - NNB
  - NR
punct_postags:
  - SF
  - SP
  - SSO
  - SSC
  - SY
stop_postags:
  - SP
  - SF
  - SE
  - SSO
  - SSC
  - SC
  - SY
  - SH
