defaults:
  - __init__
  - tagger: nltk

_config_name_: nltk
_target_: lexikanon.tokenizers.NLTKTokenizer
noun_postags:
  - NN
  - NNP
  - NNS
  - NNPS
punct_postags:
  - "."
stop_postags:
  - CC
  - CD
  - DT
  - EX
  - IN
  - LS
  - MD
  - PDT
  - POS
  - PRP
  - PRP$
  - RP
  - TO
  - UH
  - WDT
  - WP
  - WP$
  - WRB
